-- src/main/resources/schema.sql

DROP TABLE IF EXISTS matriculas;
DROP TABLE IF EXISTS trilha_competencia;
DROP TABLE IF EXISTS questionarios_iniciais;
DROP TABLE IF EXISTS usuarios;
DROP TABLE IF EXISTS trilhas;
DROP TABLE IF EXISTS competencias;


CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    area_atuacao VARCHAR(100),
    nivel_carreira VARCHAR(50),
    pilar_principal VARCHAR(50),
    data_cadastro DATE NOT NULL
);

CREATE TABLE trilhas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    descricao TEXT,
    tipo_trilha VARCHAR(50) NOT NULL,
    nivel VARCHAR(50) NOT NULL,
    carga_horaria INT NOT NULL,
    foco_principal VARCHAR(100),
    ativo BOOLEAN NOT NULL
);

CREATE TABLE competencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    categoria VARCHAR(100),
    descricao TEXT
);

CREATE TABLE trilha_competencia (
    trilha_id BIGINT NOT NULL,
    competencia_id BIGINT NOT NULL,
    PRIMARY KEY (trilha_id, competencia_id),
    FOREIGN KEY (trilha_id) REFERENCES trilhas(id),
    FOREIGN KEY (competencia_id) REFERENCES competencias(id)
);

CREATE TABLE matriculas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    trilha_id BIGINT NOT NULL,
    data_inscricao DATE NOT NULL,
    status VARCHAR(50) NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    FOREIGN KEY (trilha_id) REFERENCES trilhas(id)
);

CREATE TABLE questionarios_iniciais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    data_resposta DATE NOT NULL,
    carreira_atual VARCHAR(150),
    tempo_carreira_atual_anos INT,
    ja_trabalhou_outra_carreira BOOLEAN,
    carreiras_anteriores TEXT,
    gosta_de_fazer TEXT,
    gosta_de_estudar TEXT,
    modo_estudo_preferido VARCHAR(50),
    interesse_migracao_tipo VARCHAR(50),
    areas_interesse_futuro TEXT,
    disponibilidade_horas_semana INT,
    objetivo_carreira TEXT,
    saude_estresse INT,
    saude_energia INT,
    saude_equilibrio_vida_trabalho INT,
    saude_auto_cobranca INT,
    indice_saude_mental INT,
    nivel_saude_mental VARCHAR(50),
    risco_automacao VARCHAR(50),
    observacoes_analise TEXT,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);